<x-layouts.admin title="Policy Categories">
    <div class="flex flex-col gap-6">
        <x-page-header title="Policy Categories" description="Configure reusable categories without removing referenced policy history."><x-slot:actions><div class="flex gap-3"><a href="{{ route('admin.policies.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Back to Policies</a><a href="{{ route('admin.policy-categories.create') }}" class="rounded-lg bg-portal-900 px-4 py-2.5 text-sm font-semibold text-white">Add Category</a></div></x-slot:actions></x-page-header>
        <x-card class="overflow-hidden p-0">
            @if ($categories->isEmpty())<x-empty-state title="No policy categories" description="Create the first category to organize office policies." class="m-5" />@else
                <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Name</th><th class="px-5 py-3">Description</th><th class="px-5 py-3">Policies</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach ($categories as $category)<tr><td class="px-5 py-4 font-semibold text-slate-950">{{ $category->name }}</td><td class="px-5 py-4 text-slate-600">{{ $category->description ?: '—' }}</td><td class="px-5 py-4 text-slate-600">{{ $category->policies_count }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $category->is_active ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-200 text-slate-700' }}">{{ $category->is_active ? 'Active' : 'Inactive' }}</span></td><td class="px-5 py-4"><div class="flex justify-end gap-3"><a href="{{ route('admin.policy-categories.edit', $category) }}" class="font-semibold text-slate-700">Edit</a><form method="POST" action="{{ $category->is_active ? route('admin.policy-categories.deactivate', $category) : route('admin.policy-categories.reactivate', $category) }}" onsubmit="return confirm('{{ $category->is_active ? 'Deactivate this category? Existing policies will remain.' : 'Reactivate this category?' }}')">@csrf @if (! $category->is_active) @method('DELETE') @endif<button class="font-semibold {{ $category->is_active ? 'text-red-700' : 'text-emerald-700' }}">{{ $category->is_active ? 'Deactivate' : 'Reactivate' }}</button></form></div></td></tr>@endforeach</tbody></table></div><div class="border-t border-slate-200 px-5 py-4">{{ $categories->links() }}</div>
            @endif
        </x-card>
    </div>
</x-layouts.admin>
